"""make phone and gender required

Revision ID: 0b4d06cdd48e
Revises: c30d8f5e5a69
Create Date: 2026-06-26 21:50:49.936034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b4d06cdd48e'
down_revision: Union[str, Sequence[str], None] = 'c30d8f5e5a69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('users', 'gender',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'gender',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###
