# database
spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/event_booking_db
spring.datasource.username=postgres
spring.datasource.password=zoyakhanam

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JWT
app.jwt.secret=a18hU9IpX11BunJ9@meow89x#bZ5security-03mmZqwerty2eR
app.jwt.expiration-ms=1800000